"""Macro emission: generate ``numbers.tex`` from the ledger.

Each macro renders as a provenance comment plus a ``\\newcommand``, so the
generated file is self-explaining.  New prose references macros instead of
hand-copied digits; ``check`` guards whatever is still hand-written.
The whole file is built in memory first — any failure produces no output.
"""

from __future__ import annotations

import difflib
from pathlib import Path

from .audit import CheckState
from .errors import LedgerError
from .ledger import Ledger
from .report import _in_float_range


def render_numbers(ledger: Ledger, state: CheckState) -> str:
    if ledger.emit is None:
        raise LedgerError("ledger has no 'emit' section")
    lines = [
        "% Generated by texclaims — do not edit by hand.",
        f"% Macros: {len(ledger.emit.macros)}",
    ]
    for macro in ledger.emit.macros:
        raw = state.resolve(macro.value, f"macro '{macro.name}'")
        try:
            value = raw * macro.scale
        except OverflowError as exc:
            # Multiplying a huge integer by even the default 1.0 can fail
            # before formatting; report the macro instead of an internal error.
            raise LedgerError(
                f"macro {macro.name!r} value is out of the auditable range") from exc
        if not _in_float_range(value):
            # A macro is quoted as a result; emitting "nan" would put it in the
            # PDF and still exit 0.
            raise LedgerError(
                f"macro {macro.name!r} resolves to {value}, which is not a finite number")
        try:
            if macro.format.endswith(("d", "n")):
                rendered = format(int(round(value)), macro.format)
            elif macro.format:
                rendered = format(value, macro.format)
            else:
                rendered = f"{value:g}"
        except (ValueError, TypeError, OverflowError) as exc:
            raise LedgerError(
                f"bad format spec {macro.format!r} for macro {macro.name!r}: {exc}") from exc
        # A bare % would comment out the rest of the line in LaTeX.
        rendered = rendered.replace("%", r"\%")
        raw_text = f"{raw:.10g}" if _in_float_range(raw) else str(raw)
        lines.append(f"% {macro.name} <- {macro.value.raw} = {raw_text}")
        lines.append(f"\\newcommand{{\\{macro.name}}}{{{rendered}}}")
    return "\n".join(lines) + "\n"


def check_emitted(ledger: Ledger, state: CheckState, output: Path) -> list[str]:
    """Return a unified diff (empty when in sync) against the emitted file."""
    rendered = render_numbers(ledger, state)
    try:
        existing = output.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        raise LedgerError(f"cannot read emitted file {output}: {exc}") from exc
    if existing == rendered:
        return []
    diff = difflib.unified_diff(
        existing.splitlines(), rendered.splitlines(),
        fromfile=str(output), tofile="regenerated", lineterm="",
    )
    return list(diff)[:80]
